kind: pipeline
type: docker
name: defalue

steps:
  - name: build app
    image: maven:3.8.4-jdk-11
    volumes:
      - name: maven-build
        path: /app/build
      - name: maven-cache
        path: /root/.m2
    commands:
      - mvn clean package
      - cp target/*.jar /app/build

  - name: send telegram notification
    image: appleboy/drone-telegram
    settings:
      token:
        from_secret: BOT_TOKEN
      to:
        from_secret: USER_ID
      disable.webpage.preview: false
      message: >
        *Build #{{build.number}} of {{repo.namespace}}/{{repo.name}}*
        
        *Branch:* {{commit.branch}}
        
        *Author:* {{commit.author}} ({{commit.email}})
        
        *Commit:* [{{truncate commit.sha 8}}]({{commit.link}})
        
        *Message:* {{commit.message}}
        
        *Build Time:* {{since build.started}}
        
        *Result:* {{build.status}}
        
        *Link:* [Click me!]({{build.link}})

volumes:
  - name: maven-build
    host:
      path: /home/ubuntu/DroneVolumes/maven/build
  - name: maven-cache
    host:
      path: /home/ubuntu/DroneVolumes/maven/cache
