kind: pipeline
type: docker
name: defalue

steps:
  - name: build app
    image: maven:3.8.4-jdk-11
    volumes:
      - name: maven-build
        path: /app/build
      - name: maven-cache
        path: /root/.m2
    commands:
      - mvn clean package
      - cp target/*.jar /app/build

  - name: send telegram notification
    image: appleboy/drone-telegram
    settings:
      token:
        from_secret: BOT_TOKEN
      to:
        from_secret: USER_ID
      message: >
        #{{repo.owner}}/{{repo.name}}
        
        Build #{{build.number}} 
        
        *Branch:*
        
        {{commit.branch}}
        
        *Author:*
        
        {{commit.author}} ({{commit.email}})
        
        *Commit:*
        
        {{truncate commit.sha 8}}
        
        *Message:*
        
        {{commit.message}}
        
        *Build Number:*
        
        *Build Time:*
        
        {{since build.started}}
        
        *Result:*
        
        {{#success build.status}}
        
        Succeeded.
        
        {{else}}
        
        Failed.
        
        {{/success}}
        
        *Link:*
        
        {{build.link}}
        

volumes:
  - name: maven-build
    host:
      path: /home/ubuntu/DroneVolumes/maven/build
  - name: maven-cache
    host:
      path: /home/ubuntu/DroneVolumes/maven/cache
