kind: pipeline
type: docker
name: defalue

steps:
  - name: build
    image: maven:3.8.4-jdk-11
    volumes:
      - name: maven-build
        path: /app/build
      - name: maven-cache
        path: /root/.m2
    commands:
      - mvn clean package
      - ls -al
      - cp target/*.jar /app/build

  - name: send telegram notification
    image: appleboy/drone-telegram
    settings:
      token:
        from_secret: BOT_TOKEN
      to:
        from_secret: USER_ID
      format: html
      message: >
        <b>Repo Info:</b> <br />
        {{repo.name}}@{{commit.branch}} <br />
        <b>Author Info:</b> <br />
        {{commit.author}} ({{commit.email}}) <br />
        <b>Commit:</b> <br />
        {{truncate commit.sha 8}} <br />
        <b>Commit Message:</b> <br />
        {{commit.message}} <br />
        <b>Build Number:</b> <br />
        {{build.number}} <br />
        <b>Since:</b> <br />
        {{date build.started}} <br />
        <b>Build Time:</b> <br />
        {{since build.started}} <br />
        <b>Result:</b> <br />
        {{#success build.status}}
        Succeeded. Good job.
        {{else}}
        Failed. Fix me please.
        {{/success}}

volumes:
  - name: maven-build
    host:
      path: /home/ubuntu/DroneVolumes/maven/build
  - name: maven-cache
    host:
      path: /home/ubuntu/DroneVolumes/maven/cache
