kind: pipeline
type: docker
name: defalue

steps:
#  - name: build app
#    image: maven:3.8.4-jdk-11
#    volumes:
#      - name: maven-build
#        path: /app/build
#      - name: maven-cache
#        path: /root/.m2
#    commands:
#      - mvn clean package
#      - cp target/*.jar /app/build

  - name: build image
    image: maven:3.8.4-jdk-11
    volumes:
      - name: maven-build
        path: /app/build
      - name: maven-cache
        path: /root/.m2
      - name: docker-sock
        path: /var/run/docker.sock
    commands:
      - mvn clean spring-boot:build-image -Dspring-boot.build-image.imageName=xmuu/drone-ci-demo

  - name: push image
    image: docker:20.10.6
    environment:
      username:
        from_secret: REGISTRY_USERNAME
      password:
        from_secret: REGISTRY_PASSWORD
    volumes:
      - name: docker-sock
        path: /var/run/docker.sock
    commands:
      - docker login registry.xmuu.dev -u $username -p $username
      - docker push xmuu/drone-ci-demo

  - name: send telegram notification
    image: appleboy/drone-telegram
    settings:
      token:
        from_secret: BOT_TOKEN
      to:
        from_secret: USER_ID
      disable.webpage.preview: false
      message: >
        *Build #{{build.number}}* of `{{repo.namespace}}/{{repo.name}}`
        
        *Branch:* {{commit.branch}}
        
        *Author:* {{commit.author}} ({{commit.email}})
        
        *Commit:* `{{truncate commit.sha 8}}`
        
        *Message:* {{commit.message}}
        
        *Build Time:* {{since build.started}}
        
        *Result:* {{uppercasefirst build.status}}
        
        *Link:* [Click me!]({{build.link}})

volumes:
  - name: maven-build
    host:
      path: /home/ubuntu/DroneVolumes/maven/build
  - name: maven-cache
    host:
      path: /home/ubuntu/DroneVolumes/maven/cache
  - name: docker-sock
    host:
      path: /var/run/docker.sock